### PR TITLE
Updates dependencies & fixes tests

### PR DESCRIPTION
**Pull request by zcei**
As the last PR was just for 'downgrading' the version, here is a fixed version.

Basically it calls `knex.migrate.currentVersion()` to ensure that the migrations table is created.

It also restructures the `*.json` fixtures, so that the `database` property matches `knex`'s expectations.

``` diff
- "tableName": "knex_migrations",
+ "migrations": {
+   "tableName": "knex_migrations"
+ }
```

As a side-effect I also enhanced the `jshint` functionality, as my linter showed 17 'errors' for `knex-migrate.test.js`

### CODE REVIEW

**Comment by Yvem** [comment]
This looks great, if it was fixed. @zcei can you finish it ?

**Comment by zcei** [comment]
@Yvem: I dropped the `0.8.x` support with latest commit, so it does work.

Though it seems like @p-baleine isn't maintaining this anymore.
Feel free to reference my fork, I'll merge the changes into my `master` now:

``` json
"grunt-knex-migrate": "zcei/grunt-knex-migrate"
```

**Comment by Yvem** [comment]
This looks great. Let's nag @p-baleine to merge it ! Eventually, we'll switch to your fork. @chesleybrown seems to be maintaining a fork, too. Too bad.

**Comment by zcei** [comment]
@Yvem: it makes more sense to just do a PR at his fork, as I'm mainly using `gulp`. 
@chesleybrown: I can do the PR if you want to further maintain this grunt plugin?
@p-baleine: No comments from your side? In case Chesley wants to push this further it might be good to hand over the `npm` package to him - then you don't have to mind our pings hehe :grin:

**Comment by chesleybrown** [comment]
My fork only fixed two things:
1. It makes the grunt command `fail` when the migration was unsuccessful instead of just printing an error and continuing.
2. It specifies the ~0.7.5 knex version as the newer versions caused some warnings (it would require some changes to the grunt task to resolve the warnings which I didn't get time to apply yet)

**Pull request closed without merging**
